// <auto-generated />
namespace DikuSharp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-beta1-30206")]
    public sealed partial class ItemRoomRelationship3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ItemRoomRelationship3));
        
        string IMigrationMetadata.Id
        {
            get { return "201405130218288_ItemRoomRelationship3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
